export enum GenericErrors {
    GOOGLE_ERROR = 'GOOGLE_ERROR',
    PRISMA_ERROR = 'PRISMA_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    SERVER_ERROR = 'SERVER_ERROR',
    NODEMAILER_ERROR = 'NODEMAILER_ERROR',
}

export enum LoginErrors {
    EMAIL_NOT_REGISTERED = 'EMAIL_NOT_REGISTERED',
    WRONG_HASH = 'WRONG_HASH',
    WRONG_PASSWORD = 'WRONG_PASSWORD',
}

export enum SignupErrors {
    EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
    ERROR_CREATING_USER = 'ERROR_CREATING_USER',
    ERROR_CREATING_DOCTOR = 'ERROR_CREATING_DOCTOR',
}

export enum GoogleErrors {
    NO_REFRESH_TOKEN = 'NO_REFRESH_TOKEN',
    ERROR_FETCHING_EVENTS = 'ERROR_FETCHING_EVENTS',
}

export enum AddClientErrors {
    IS_ALREADY_PATIENT = 'IS_ALREADY_PATIENT',
}

export enum SettingsMessages {
    ACCOUNT_DELETED = 'ACCOUNT_DELETED',
}

export enum ServiceErrors {
    MISSING_INPUT_NAME = 'MISSING_INPUT_NAME',
    MISSING_INPUT_DESCRIPTION = 'MISSING_INPUT_DESCRIPTION',
    MISSING_INPUT_DURATION = 'MISSING_INPUT_DURATION',
    MISSING_INPUT_LOCATION = 'MISSING_INPUT_LOCATION',
    MISSING_INPUT_PRICE = 'MISSING_INPUT_PRICE',
    MISSING_INPUT_MULTIPRICE = 'MISSING_INPUT_MULTIPRICE',
    MISSING_PARAM_ID = 'MISSING_PARAM_ID',
    NAME_ALREADY_EXISTS = 'NAME_ALREADY_EXISTS',
    DESCRIPTION_ALREADY_EXISTS = 'DESCRIPTION_ALREADY_EXISTS',
}

export enum LocationErrors {
    MISSING_INPUT_ALIAS = 'MISSING_INPUT_ALIAS',
    MISSING_INPUT_ADDRESS = 'MISSING_INPUT_ADDRESS',
    ALIAS_ALREADY_EXISTS = 'ALIAS_ALREADY_EXISTS',
    ADDRESS_ALREADY_EXISTS = 'ADDRESS_ALREADY_EXISTS',
}

export enum PatientErrors {
    MISSING_INPUT_FIRSTNAME = 'MISSING_INPUT_FIRSTNAME',
    MISSING_INPUT_LASTNAME = 'MISSING_INPUT_LASTNAME',
    MISSING_INPUT_EMAIL = 'MISSING_INPUT_EMAIL',
    MISSING_INPUT_PHONE = 'MISSING_INPUT_PHONE',
}

export enum AppointmentErrors {
    MISSING_INPUT_PATIENTS = 'MISSING_INPUT_PATIENTS',
    MISSING_INPUT_SERVICE = 'MISSING_INPUT_SERVICE',
    MISSING_INPUT_DURATION = 'MISSING_INPUT_DURATION',
    MISSING_INPUT_LOCATION = 'MISSING_INPUT_LOCATION',
    MISSING_INPUT_RELATION = 'MISSING_INPUT_RELATION',
    MISSING_INPUT_PRICE = 'MISSING_INPUT_PRICE',
    MISSING_INPUT_DATE = 'MISSING_INPUT_DATE',
    MISSING_INPUT_TIME = 'MISSING_INPUT_TIME',
}

export enum SuccessCodes {
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NO_CONTENT = 204,
    FOUND = 302,
}

export enum ErrorCodes {
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    INTERNAL_SERVER_ERROR = 500,
    SERVICE_UNAVAILABLE = 503,
    CUSTOM_ERROR = 777,
}

/**
 * This enum MUST map 1 to 1 to what is in the DoctorSpeciality database table
 */
export enum DoctorSpecialty {
    PSYCHOLOGY = 'Psicologia',
}
